name: Deploy to 

on:
  push:
    branches: [ "main" ]

env:
  http_proxy: "http://120.78.133.243:3128"
  https_proxy: "http://120.78.133.243:3128"
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    #- name: Checkout
    #  uses: actions/checkout@v4

    - name: Set up environment variables
      run: |
        export  HTTP_PROXY=${{ env.http_proxy }}
        export  HTTPS_PROXY=${{ env.https_proxy }}
    - name: Get url one
      run: |
        curl http://cip.cc
    - name: Get url two
      run: |
        curl https://checkip.amazonaws.com
        

