name: Deploy to 

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    #environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up environment variables
      env:
        HTTP_PROXY: http://120.78.133.243:3218
        HTTPS_PROXY: https://120.78.133.243:3218
        
    - name: get proxy eip
      run: |
        curl --proxy $HTTP_PROXY http://cip.cc
        


