name: Deploy to 

on:
  push:
    branches: [ "main" ]

env:
  http_proxy: "http://120.78.133.243:3218"
  https_proxy: "https://120.78.133.243:3218"
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up environment variables
      run: |
        #export  HTTP_PROXY=${{ env.http_proxy }}
        #export  HTTPS_PROXY=${{ env.https_proxy }}
        echo ${{ env.http_proxy }}


